---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Oracle Restore Tasks
      include_tasks: oracle_restore.yml
      tags:
        - ontap_oracle_restore
