# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Turn off Oracle DB backup mode after snapshots 
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Copy backup script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_bkup_mode.sh
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - cp_bkup_script_end

    - name: Turn off backup mode for each DB registered in /etc/oratab 
      shell: "{{ script_dir }}/ora_bkup_mode.sh end_bkup"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exe_end_bkup
