- name: CVO Setup
  hosts: localhost
  gather_facts: False
  collections:
    - netapp.cloudmanager
    - netapp.ontap
    - community.aws
  vars_files:
    - roles/cvo_setup/defaults/main.yml
  roles:
    - role: cvo_setup
  tags:
    - cvo_config