# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Put Oracle DB in backup mode before snapshots to ensure app consistency
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Copy backup script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_bkup_mode.sh 
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - cp_bkup_script_begin

    - name: Enable backup mode for each DB registered in /etc/oratab 
      shell: "{{ script_dir }}/ora_bkup_mode.sh begin_bkup"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exe_begin_bkup
