#################################################################
#################################################################
- block:
    - name: Create Snapmiror Policy
      na_ontap_snapmirror_policy:
        hostname: "{{ dst_cluster_ip }}"
        username: "{{ dst_cluster_username }}"
        password: "{{ dst_cluster_password }}"
        state: present
        vserver: "{{ dst_vserver }}"
        policy_name: "{{ snapmirror_policy }}"
        policy_type: async_mirror
        comment: "Created by Ansible"
        https: true
        validate_certs: false
      tags:
        - ontap_snapmirror_policy

    - name: Create ONTAP/ONTAP SnapMirror
      na_ontap_snapmirror:
        hostname: "{{ dst_cluster_ip }}"
        username: "{{ dst_cluster_username }}"
        password: "{{ dst_cluster_password }}"
        state: present
        source_endpoint:
          cluster: "{{ src_cluster_name }}"
          path: "{{ src_vserver + ':' + item.0 }}"
        destination_endpoint:
          cluster: "{{ dst_cluster_name }}"
          path: "{{ dst_vserver + ':' + item.1 }}"
        initialize: true
        create_destination:
          enabled: true
        policy: "{{ snapmirror_policy }}"
        relationship_type: extended_data_protection
        https: true
        validate_certs: false
        use_rest: always
      register: snapmirror_create
      with_together:
        - "{{ src_cg_vols }}"
        - "{{ dst_cg_vols }}"
      tags:
        - ontap_snapmirror
  rescue:
    - name: Failure
      fail:
        msg:
        - Create destination volume for SnapMirror failed with error - "{{ snapmirror_create.stderr }}"
        - Possible troubleshooting steps:
        - 1. Check if ONTAP API is reachable
        - 2. Check if variables defined adhere to the guidelines
