---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Recover all Oracle DBs on a host after snapshot restore
      include_tasks: ora_reco.yml
      tags: 
        - cp_reco_script
        - exe_reco_script
