# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Recover Oracle DB until recovery point desired after a snapshot restore
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Copy recovery script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_recovery.sh 
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
#      become_user: '{{ oracle_user }}'
      tags:
        - cp_reco_script

    - name: Recover each DB registered in /etc/oratab in running mode
      shell: "{{ script_dir }}/ora_recovery.sh {{ recovery_type }} {{ recovery_point }}"
      become: true
#      become_user: '{{ oracle_user }}'
      tags:
        - exe_reco_script
