# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Recover Oracle DB until recovery point desired after a snapshot restore
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Sync up control files before DB recovery on Oracle DB servers
      ansible.builtin.copy:
        src: '{{ control_files[1] }}'
        dest: '{{ control_files[0] }}'
        remote_src: yes
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - sync_control_file

    - name: Copy relink script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_relink.sh
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
      tags:
        - cp_relink_script

    - name: Relink Oracle binary before DB recovery
      shell: "{{ script_dir }}/ora_relink.sh }}"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exe_relink_script

    - name: Copy recovery script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_recovery.sh 
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
      tags:
        - cp_reco_script

    - name: Recover each DB registered in /etc/oratab in running mode
      shell: "{{ script_dir }}/ora_recovery.sh {{ recovery_type }} {{ recovery_point }}"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exe_reco_script
