---
#Disable SELinux
- block:
    - name: Disable SELinux
      selinux: 
        state: disabled
      become: true
      tags:
        - disable_selinux

#Disable Firewall Deamon
    - name: Disable firewall deamon (firewalld)
      service: 
        name: firewalld 
        state: stopped
        enabled: no
      become: true
      tags:
        - disable_firewall
