---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# RedHat Linux 7 specific configuration
# Register subscrtipion and install preinstall rpm for Oracle DB
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------

- block:
    - name: Configure RedHat 7 for Oracle DB installation
      when: ansible_facts ['distribution'] == "RedHat" and ansible_facts ['distribution_major_version'] == "7"
      include_tasks: rhel7_config.yml
      tags:
        - register_subscription_el7
        - enable_optional_rpms_el7
        - cp_preinstall-19c_rpm_el7
        - inst_preinstall-19c_rpm_el7
        - inst_compat-libstdc++-33
        - inst_gcc-c++

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# RedHat Linux 8 specific configuration
# Register subscrtipion and install preinstall rpm for Oracle DB
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Configure RedHat 8 for Oracle DB installation
      when: ansible_facts ['distribution'] == "RedHat" and ansible_facts ['distribution_major_version'] == "8"
      include_tasks: rhel8_config.yml
      tags:
        - register_subscription_el8
        - cp_preinstall-19c_rpm_el8
        - inst_preinstall-19c_rpm_el8
        - cp_compat-libcap1-1.10_el8
        - inst_compat-libcap1-1.10_el8

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Oracle Linux specific configuration
# Install required packages, copy and install rpm
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Configure Oracle Linux for Oracle DB installation
      when: ansible_facts ['distribution'] == "OracleLinux"
      include_tasks: ol_config.yml
      tags:
        - inst_preinstall-19c_rpm
        - cp_compat-libcap1-1.10
        - inst_compat-libcap1-1.10

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Disable transparent hugepages in current system
# Disable transparent hugepages at reboot
# Configure Kernel for hugepages
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Disable transparent hugepages and configure kernel for hugepages
      include_tasks: huge_pages.yml
      tags:
        - disable_thp
        - config_hugepages

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Disable SELinux
# Disable Firewall Deamon
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Disable firewall deamon/SELinux
      include_tasks: disable_se.yml
      tags:
        - disable_selinux
        - disable_firewall

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Enable chronyd service
# Start chronyd service
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Enable chronyd and Start chronyd service
      include_tasks: enable_chronyd.yml
      tags:
        - enable_chronyd
        - start_chronyd

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Increase file descriptor hard limit
# Increase min stack size
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Increase file descriptor hard limit
      include_tasks: descriptor_limit.yml

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create pam.d Session File
# Enable limits change without reboot
# Create a pam.d Session non-interactive file
# Add a line to enable limits change without reboot
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name:  Create Session Files
      include_tasks: session_files.yml
