---
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Create mount points for NFS file systems
# Mount NFS file systems on Oracle hosts
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------

- block:
    - name: Create mount points for NFS file systems / Mount NFS file systems on Oracle hosts
      include_tasks: mount_points.yml
      tags:
        - cre_mount_points
        - mount_host_datastores

# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Check mount points for NFS file system
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
    - name: Verify NFS Mounts
      include_tasks: verify_mounts.yml
      tags:
        - verify_nfs_mounts
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
