- block:
######## Get Connector IP #############
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - "{{ connector.msg.instance_id }}"
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*]') }}"
    - debug: var=msg[0].private_ip_address
    
######## Create Access Token with username/password #############
    - name: Create access token with username/password
      uri:
        url: "https://netapp-cloud-account.auth0.com/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: password
          username: "{{ email_id }}"
          password: "{{ cm_password }}"
          audience: "https://api.cloud.netapp.com"
          scope: profile
          client_id: "{{ regular_id }}"
        headers:
          Content-Type: application/json
      register: connector_accesstoken
      when: connector_access == "pass" 
    - set_fact: access="{{ connector_accesstoken.json.access_token }}"
      when: connector_access == "pass"
      
######## Create Access Token with Refresh Token #############      
    - name: Create access token with refresh token
      uri:
        url: "https://netapp-cloud-account.auth0.com/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: refresh_token
          refresh_token: "{{ token }}"
          client_id: "{{ sso_id }}"
        headers:
          Content-Type: application/json
      register: connector_accesstoken
      when: connector_access == "refresh_token" 
    - set_fact: access="{{ connector_accesstoken.json.access_token }}"
      when: connector_access == "refresh_token"  
    
################## Get Workspace ID ###################
    - name: Get Workspace ID
      uri:
        url: "https://cloudmanager.cloud.netapp.com/tenancy/account/{{ account }}/workspace"
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ access }}"
      register: result
    - set_fact:
        msgs: "{{ result | json_query('json[0]') }}"
    - debug: var=msgs.workspacePublicId
      
################## Create on Prem Connection ###################
    - name: Add on-prem ONTAP cluster to connector in Cloud Manager
      uri:
        url: "http://{{ msg[0].private_ip_address }}/occm/api/onprem/working-environments"
        method: POST
        body_format: json
        body:
          tenantId: "{{ msgs.workspacePublicId }}"
          name: "{{ src_cluster_name }}"
          clusterAddress: "{{ src_cluster_ip }}"
          clusterUserName: "{{ src_cluster_username }}"
          clusterPassword: "{{ src_cluster_password }}"
          location: ON_PREM
        headers:
          Content-Type: application/json
          Authorization: "{{ access }}"
  rescue:
    - name: Failure 
      fail:
        msg: 
        - Add on-prem ONTAP cluster to connector in Cloud Manager failed!
        - Possible troubleshooting steps:
        - 1. Check if connector API endpoint is reachable 
        - 2. Check if provided workspace_id and on-prem ONTAP cluster details are correct
        - 3. Check if variables defined adhere to the guidelines
