- block:
######## Get Connector IP #############
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - "{{ connector.msg.instance_id }}"
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*].private_ip_address') }}"
    - debug: var=msg
    
######## Create Access Token with username/password #############
    - name: Create access token with username/password
      uri:
        url: "https://netapp-cloud-account.auth0.com/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: password
          username: "{{ email_id }}"
          password: "{{ password }}"
          audience: "https://api.cloud.netapp.com"
          scope: profile
          client_id: QC3AgHk6qdbmC7Yyr82ApBwaaJLwRrNO
        headers:
          Content-Type: application/json
      register: connector_accesstoken
      when: connector_access == "password"
      
######## Create Access Token with Refresh Token #############      
    - name: Create access token with refresh token
      uri:
        url: "https://netapp-cloud-account.auth0.com/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: refresh_token
          refresh_token: "{{ token }}"
          client_id: Mu0V1ywgYteI6w1MbD15fKfVIUrNXGWC
        headers:
          Content-Type: application/json
      register: connector_accesstoken
      when: connector_access == "refresh_token"
    - debug: var=connector_accesstoken
    
################## Get Workspace ID ###################
    - name: Get Workspace ID
      uri:
        url: "https://cloudmanager.cloud.netapp.com/tenancy/account/{{ account }}/workspace"
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ connector_accesstoken.json.access_token }}"
      register: result
      
################## Create on Prem Connection ###################
    - name: Add on-prem ONTAP cluster to connector in Cloud Manager
      uri:
        url: "http://{{ msg }}/occm/api/onprem/working-environments"
        method: POST
        body_format: json
        body:
          tenantId: "{{ result.workspacePublicId }}"
          name: "{{ src_cluster_name }}"
          clusterAddress: "{{ src_cluster_ip }}"
          clusterUserName: "{{ src_cluster_username }}"
          clusterPassword: "{{ src_cluster_password }}"
          location: ON_PREM
        headers:
          Content-Type: application/json
          Authorization: "{{ connector_accesstoken.json.access_token }}"
  tags:
    - on_prem_connect
  rescue:
    - name: Failure 
      fail:
        msg: 
        - Add on-prem ONTAP cluster to connector in Cloud Manager failed!
        - Possible troubleshooting steps:
        - 1. Check if connector API endpoint is reachable 
        - 2. Check if provided workspace_id and on-prem ONTAP cluster details are correct
        - 3. Check if variables defined adhere to the guidelines
