- block:

    
################## Get Workspace ID ###################
    - name: Get Workspace ID
      uri:
        url: "https://cloudmanager.cloud.netapp.com/tenancy/account/{{ account }}/workspace"
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          Authorization: "Bearer {{ connector_accesstoken.json.access_token }}"
      register: result
    - debug: var=result
  tags:
     on_prem_connect
   
