- block:
######## Get Connector IP #############
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - "{{ connector.msg.instance_id }}"
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*]') }}"
    - debug: var=msg.private_ip_address
  tags:
    - on_prem_connect
