- block:

    
################## Get Workspace ID ###################
    - name: Get Workspace ID
      uri:
        url: "https://cloudmanager.cloud.netapp.com/tenancy/account/{{ account }}/workspace"
        method: GET
        return_content: yes
        headers:
          Content-Type: application/json
          Authorization: "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik5rSXlPVFUzUWpZek1ESkRPVGd5TlRJMU1EUkZNVFpFUTBFd1JEUkJRVGxFT1VFMU5UUkNOZyJ9.eyJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9mdWxsX25hbWUiOiJBaG1hZCBTdWZpYW4iLCJodHRwOi8vY2xvdWQubmV0YXBwLmNvbS9lbWFpbF92ZXJpZmllZCI6ZmFsc2UsImh0dHA6Ly9jbG91ZC5uZXRhcHAuY29tL2Nvbm5lY3Rpb25faWQiOiJjb25fdk5DdjdsdjBKa2t5OWxMZCIsImh0dHA6Ly9jbG91ZC5uZXRhcHAuY29tL2lzX2ZlZGVyYXRlZCI6dHJ1ZSwiaHR0cDovL2Nsb3VkLm5ldGFwcC5jb20vaW50ZXJuYWwiOiJOZXRBcHAiLCJpc3MiOiJodHRwczovL25ldGFwcC1jbG91ZC1hY2NvdW50LmF1dGgwLmNvbS8iLCJzdWIiOiJ3YWFkfEg0dTFtY3c0OGppaEc3RVJ5MHY0SlFJLUdlQ2FkY2htb0NUdWlpeVZSTXMiLCJhdWQiOiJodHRwczovL2FwaS5jbG91ZC5uZXRhcHAuY29tIiwiaWF0IjoxNjMyODY3Mzg5LCJleHAiOjE2MzI5NTM3ODksImF6cCI6Ik11MFYxeXdnWXRlSTZ3MU1iRDE1ZktmVklVck5YR1dDIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCJ9.jplormITzV6Xu4ALH-7ArAcOdZQoiiVEyuOci0YvCYu2oB8vXR3vHvbdbvFaEhquxQayR55yLXPPDt9vUlo9JD6pCT4WSlFWxyWf6ngMC3zVsf4qMSmcozOfaz3Cm3eemw2tezBooyCVaVZbDliC7jD6OsrnQ-4cWLHadwLAAtgitpEW5dIs6F0Gz-qx1JOveVFZK_m54dKhwl47HqEBPHR-WnsW3sGJu9FXK6d1ceVSP9SjP4Umnu30BESUetZZozKNeresYvdgyOo2YQBKc9sY3daVUN8VIDo6I22BWQkxsKtUuLKPtG6BB9NuPjcVi73goh767AY1VpBIdn2-OQ"
      register: result
    - debug: var=result.content[0]
  tags:
     on_prem_connect
   
