- block:
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - i-057cbbd865e1187f0
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*].private_ip_address') }}"
    - debug: var=msg
  tags:
    - on_prem_connect
 
