- block:
######## Get Connector IP #############
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - i-0462f521cdce6b8fc
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*]') }}"
    - debug: var=msg
  tags:
    - on_prem_connect
