- block:
######## Get Connector IP #############
    - name: Gather Connector IP Address
      ec2_instance_info:
        instance_ids:
          - "{{ connector.msg.instance_id }}"
      register: connector_info
    - set_fact:
        msg: "{{ connector_info | json_query('instances[*].private_ip_address') }}"
    - debug: var=msg[0]

