---
##### Deploy NetApp Cloud Manager Connector #######
- name: Create NetApp Cloud Manager connector for AWS
  netapp.cloudmanager.na_cloudmanager_connector_aws:
    state: present
    refresh_token: "{{ token }}"
    name: "{{ connector_name }}"
    region: "{{ region_deploy }}"
    key_name: "{{ key_pair }}"
    subnet_id: "{{ subnet }}"
    security_group_ids: "{{ security_group }}"
    iam_instance_profile_name: "{{ aws_role_name }}"
    account_id: "{{ account }}"
    company: NetApp
    associate_public_ip_address: false
  register: connector
#- debug:
#    msg: "my connector {{ connector }}"

#    proxy_url: abc.com
#    proxy_user_name: xyz
#    proxy_password: abcxyz
#    proxy_certificates: [abc.crt.txt, xyz.crt.txt]
#    aws_tag: [
#        {tag_key: abc,
#        tag_value: a123}]


######## Delay to build connector ###############

- name: Pause for 2 minutes to build connector
  pause:
    minutes: 2
