############################# Create Access Token ##################
- block:
    #- name: Create access token with username/password
    #  uri:
    #    url: "https://netapp-cloud-account.auth0.com/oauth/token"
    #    method: POST
    #    body_format: json
    #    body:
    #      grant_type: password
    #      username: ""
    #      password: ""
    #      audience: "https://api.cloud.netapp.com"
    #      scope: profile
    #      client_id:
    #    headers:
    #      Content-Type: application/json
    #  register: connector_accesstoken
    #  when: connector_access == "password"
    - name: Create access token with refresh token
      uri:
        url: "https://netapp-cloud-account.auth0.com/oauth/token"
        method: POST
        body_format: json
        body:
          grant_type: refresh_token
          refresh_token: ""
          client_id:
        headers:
          Content-Type: application/json
      register: token_refreshtoken_register
    - debug: var=token_refreshtoken_register.json.access_token
  rescue:
    - name: Failure
      fail:
        msg:
        - Create access token failed!
        - Possible troubleshooting steps:
        - 1. Check if API endpoint [https://netapp-cloud-account.auth0.com/oauth/token] is reachable
        - 2. Check if provided username/password or refresh_token are correct
        - 3. Check if variables defined adhere to the guidelines


################### Create Snapmirror ###################
- block:
    - name: Create Snapmirror from On-Prem to CVO
      uri:
        url: "http://172.30.0.186/occm/api/replication/vsa"
        method: POST
        body_format: json
        body:
          replicationRequest:
            sourceWorkingEnvironmentId: "OnPremWorkingEnvironment-"
            destinationWorkingEnvironmentId: "VsaWorkingEnvironment-"
            sourceInterclusterLifIps:
              - "10.61.185.78"
            destinationInterclusterLifIps:
              - "172.30.10.48"
            policyName: "MirrorAllSnapshots"
            #maxTransferRate: "1024"
            #client_id: "8viO1aWuuYsULEvdlvCteSiCyWkfZAi1clients"
          replicationVolume:
            sourceSvmName: "svm0"
            sourceVolumeName: "source"
            destinationVolumeName: "newone1"
            destinationAggregateName: "aggr1"
            #numOfDisksApprovedToAdd: 2
            advancedMode: false
        headers:
          Content-Type: application/json
          Authorization: "{{ token_refreshtoken_register.json.access_token }}"
      register: result
      failed_when:
        - ' "202" not in result.msg '
        - ' "200" not in result.msg '
  rescue:
    - name: Failure
      fail:
        msg:
        - Snapmirror failed!
        - Possible troubleshooting steps:
        - 1. Check if API endpoint [https://netapp-cloud-account.auth0.com/oauth/token] is reachable
        - 2. Check if provided username/password or refresh_token are correct
        - 3. Check if variables defined adhere to the guidelines
