#################################################################
#################################################################
- block:
    - name: Create Snapmiror Policy
      netapp.ontap.na_ontap_snapmirror_policy:
        hostname: "{{ dst_cluster_ip }}"
        username: "{{ dst_cluster_username }}"
        password: "{{ dst_cluster_password }}"
        state: present
        vserver: "{{ dst_vserver }}"
        policy_name: "{{ snapmirror_policy }}"
        policy_type: async_mirror
        comment: "Created by Ansible"
        https: true
        validate_certs: false

    - name: Obtain Oracle Consistency Group Volumes
      set_fact:
        src_cg_vols: "{{ src_orabinary_vols + src_db_vols + src_archivelog_vols }}"
    - debug:
        msg: "Source Consistency Group Volumes {{ src_cg_vols }}"

    - name: Create ONTAP/ONTAP SnapMirror
      netapp.cloudmanager.na_cloudmanager_snapmirror:
        state: present
#        source_working_environment_name: "{{ src_cluster_name }}"
        source_working_environment_id: OnPremWorkingEnvironment-HauAk0XV
        destination_working_environment_id: VsaWorkingEnvironment-zE7ZBzPM
        source_volume_name: "{{ item }}"
#        destination_working_environment_name: "{{ cvo_name }}"
        destination_volume_name: "{{ 'dr_' + item }}"
        policy: MirrorAllSnapshots 
        client_id: "zzUFO6Sf6i4eu2Jm9mG9QutjquiWCUv5"
        refresh_token: "{{ token }}"
        source_svm_name: ora_svm01
      with_items:
        - "{{ src_cg_vols }}"
  tags:
    - ontap_snapmirror_create
    - ontap_snapmirror_policy
    - ontap_snapmirror
#  rescue:
#    - name: Failure
#      fail:
#        msg:
#        - Create destination volume for SnapMirror failed with error - "{{ snapmirror_create.stderr }}"
#        - Possible troubleshooting steps:
#        - 1. Check if ONTAP API is reachable
#        - 2. Check if variables defined adhere to the guidelines


############################# Create Access Token ##################
#- block:
#    - name: Create access token with username/password
#      uri:
#        url: "https://netapp-cloud-account.auth0.com/oauth/token"
#        method: POST
#        body_format: json
#        body:
#          grant_type: password
#          username: "{{ email_id }}"
#          password: "{{ password }}"
#          audience: "https://api.cloud.netapp.com"
#          scope: profile
#          client_id: QC3AgHk6qdbmC7Yyr82ApBwaaJLwRrNO
#        headers:
#          Content-Type: application/json
#      register: connector_accesstoken
#      when: connector_access == "password"
#    - name: Create access token with refresh token
#      uri:
#        url: "https://netapp-cloud-account.auth0.com/oauth/token"
#        method: POST
#        body_format: json
#        body:
#          grant_type: refresh_token
#          refresh_token: "{{ token }}"
#          client_id: "Mu0V1ywgYteI6w1MbD15fKfVIUrNXGWC"
#        headers:
#          Content-Type: application/json
#      register: connector_accesstoken
#      when: connector_access == "refresh_token"
#    - debug: var=connector_accesstoken
#  rescue:
#    - name: Failure 
#      fail:
#        msg: 
#        - Create access token failed!
#        - Possible troubleshooting steps:
#        - 1. Check if API endpoint [https://netapp-cloud-account.auth0.com/oauth/token] is reachable 
#        - 2. Check if provided username/password or refresh_token are correct
#        - 3. Check if variables defined adhere to the guidelines

################### Create Snapmirror ###################
#- block:
#    - name: Create Snapmirror from On-Prem to CVO
#      uri:
#        url: "http://{{ connector_ips }}/occm/api/replication/vsa"
#        method: POST
#        body_format: json
#        body:
#          replicationRequest:
#            sourceWorkingEnvironmentId: "{{ on_prem_id }}"
#            destinationWorkingEnvironmentId: "{{ dest_cvo_id }}"
#            sourceInterclusterLifIps: "{{ source_ic_lifs }}"
#            destinationInterclusterLifIps: "{{ dest_ic_lifs }}"
#            policyName: "{{ cvo_snap_policy }}"
#            #maxTransferRate: "1024"
#          replicationVolume:
#            sourceSvmName: "{{ source_svm }}"
#            sourceVolumeName: "{{ source_vol }}"
#            destinationVolumeName: "{{ dest_vol }}"
#            destinationAggregateName: "{{ dest_aggrg }} "
#            #numOfDisksApprovedToAdd: 2
#            advancedMode: false
#        headers:
#          Content-Type: application/json
#          Authorization: "{{ connector_accesstoken.json.access_token }}"
#      register: result
#      failed_when:
#        - ' "202" not in result.msg '
        
#  rescue:
#    - name: Failure
#      fail:
#        msg:
#        - Snapmirror failed!
#        - Possible troubleshooting steps:
#        - 1. Check if API endpoint [https://netapp-cloud-account.auth0.com/oauth/token] is reachable
#        - 2. Check if provided username/password or refresh_token are correct
#        - 3. Check if variables defined adhere to the guidelines
