---
##### Install Boto3 and awscli #####
- name: Install the pre-reqs for connector
  become: yes
  pip:
    name:
       - boto3
       - chardet
       - urllib3
       - requests
       - awscli
       - pexpect
  tags:
    - pre_check

- name: Run aws configure
  expect:
    command: aws configure
    responses:
      AWS Access Key ID: "AKIATCFKZXU6FYU76P67"
      AWS Secret Access Key: "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"
      Default region name: "us-east-1"
      Default output format: ""
  no_log: false


########## Create Role ############
#- name: Create Role
#  iam_role:
#    name: occm_sufian1
#    assume_role_policy_document:
#    state: present
#    validate_certs: true
#    aws_access_key: ""
#    aws_secret_key: ""



##### Export AWS Environment Keys and region info #####
#- name: Echo AWS keys
#  shell: "echo $AWS_ACCESS_KEY_ID"
#  environment:
#    AWS_ACCESS_KEY_ID: "{{ access_key }}"
#  tags:
#    - pre_check
#- name: Echo AWS password keys
#  shell: "echo $AWS_SECRET_KEY_ID"
#  environment:
#    AWS_SECRET_KEY_ID: "{{ secret_key }}"
#  tags:
#    - pre_check
#- name: Echo AWS password keys
#  shell: "echo $AWS_REGION"
#  environment:
#    AWS_REGION: us-east-1
#  tags:
#    - pre_check
