---
##### Install Boto3 and awscli #####
- name: Install the pre-reqs for connector
  become: yes
  pip:
    name:
       - boto3
       - chardet
       - urllib3
       - requests
       - awscli
       - pexpect
  tags:
    - pre_check


########## Create Role ########
- name: Create Role
  iam_role:
    name: occm_sufian2
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    validate_certs: true
    managed_policies:
      - arn:aws:iam::210811600188:policy/OCCM
    state: present
  tags:
    - pre_check


