---
- name: Get all available subsets
  netapp.cloudmanager.na_cloudmanager_info:
    client_id: bxsqhNLDAAkio7Cfdy5GeCZza5NhRfaeclients
    refresh_token: "{{ token }}"
    gather_subsets:
      - all
  tags:
    - pre_check    
##### Check some pre-checks for Centos8 #####
- name: Install the pre-reqs for connector
  become: yes
  pip:
    name:
       - boto3
       - chardet
       - urllib3
       - requests
       - awscli
       - pexpect
  tags:
    - pre_check

##### Running Credentials ########
- name: Run aws configure
  expect:
    command: aws configure
    responses:
      AWS Access Key ID:  "{{ access_key }}"                                                                                    
      AWS Secret Access Key: "{{ secret_key }}"                                                                                
      Default region name: "{{ region_deploy }}"
      Default output format: ""
  no_log: true

  tags:
    - pre_check


########## Create Role ########
- name: Create Role
  iam_role:
    name: "{{ aws_role_name }}"
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    validate_certs: false
    managed_policies:
      - arn:aws:iam::210811600188:policy/OCCM
    state: present
  tags:
    - pre_check


########################################################

- name: Pause for 2 minutes to Create Iam Instance Profile
  pause:
    minutes: 2
#  tags:
#    - pre_check


