---  

##### Check some pre-checks for Centos8 #####
- name: Install the pre-reqs for connector
  become: yes
  pip:
    name:
       - boto3
       - chardet
       - urllib3
       - requests
       - awscli
       - pexpect


##### Running Credentials ########
- name: Run aws configure
  expect:
    command: aws configure
    responses:
      AWS Access Key ID:  "{{ access_key }}"                                                                                    
      AWS Secret Access Key: "{{ secret_key }}"                                                                                
      Default region name: "{{ region_deploy }}"
      Default output format: ""
  no_log: true




########## Create Role ########
- name: Create Role
  iam_role:
    name: "{{ aws_role_name }}"
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    validate_certs: false
    managed_policies:
      - "{{ aws_policy }}"
    state: present



########################################################

- name: Pause for 2 minutes to Create Iam Instance Profile
  pause:
    minutes: 2




