- block:
    - name: Obtain Oracle Consistency Group Volumes
      set_fact:
        src_cg_vols: "{{ src_orabinary_vols + src_db_vols }}"
    - debug:
        msg: "Source Consistency Group Volumes {{ src_cg_vols }}"

    - name: ONTAP Info
      netapp.ontap.na_ontap_info:
        hostname: "{{ src_cluster_ip }}"
        username: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        http_port: null
        https: true
        validate_certs: false
        gather_subset: "clock_info"
      register: ontap_time
      tags:
        - ontap_time

    - set_fact:
        temp: "{{ ontap_time.ontap_info.clock_info.local_time }}"

    - set_fact:
        readable_format: "{{ '%Y-%m-%d:%H:%M:00' | strftime(temp) }}"

    - name: Consistency Group Snapshot
      netapp.ontap.na_ontap_cg_snapshot:
        hostname: "{{ src_cluster_ip }}"
        username: "{{ src_cluster_username }}"
        password: "{{ src_cluster_password }}"
        state: present
        use_rest: Always
        vserver: "{{ src_vserver }}"
        snapshot: "{{ cg_snapshot_name_prefix + '.' + readable_format }}"
        volumes: "{{ src_cg_vols }}"
        snapmirror_label: "{{ cg_snapshot_name_prefix }}"
      tags:
        - ontap_cg_snapshot
    
    - name: Snapmirror Update for DB and Binary Oracle Volumes
      na_ontap_command:
        hostname: "{{ dst_cluster_ip }}"
        username: "{{ dst_cluster_username }}"
        password: "{{ dst_cluster_password }}"
        command: "['snapmirror', 'update', '-destination-path', '{{ dst_vserver + ':' + 'dr_' + item }}', '-source-snapshot', '{{ cg_snapshot_name_prefix + '.' + readable_format }}']"
        https: true
        validate_certs: false
      with_items:
        - "{{ src_cg_vols }}"
      tags:
        - ontap_snapmirror_update

  rescue:
    - name: Failure
      fail:
        msg:
        - Create destination volume for SnapMirror failed with error - "{{ oracle_replication.stderr }}"
        - Possible troubleshooting steps:
        - 1. Check if ONTAP API is reachable
        - 2. Check if variables defined adhere to the guidelines
