# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
# Put Oracle DB in backup mode before snapshots to ensure app consistency
# ----------------------------------------------------------------------------------------------------------------------
# ----------------------------------------------------------------------------------------------------------------------
- block:
    - name: Copy switch log script to target Oracle DB servers
      ansible.builtin.copy:
        src: ora_switch_log.sh 
        dest: '{{ script_dir }}'
        owner: '{{ oracle_user }}'
        group: '{{ oracle_install_group }}'
        mode: 0755
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - cp_switch_log_script

    - name: Switch current log for each DB registered in /etc/oratab 
      shell: "{{ script_dir }}/ora_switch_log.sh"
      become: true
      become_user: '{{ oracle_user }}'
      tags:
        - exe_switch_log_script
